nelmio_cors:
  defaults:
    allow_origin: ["*"] # Autoriser toutes les origines
    allow_credentials: false
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: []
    allow_methods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"]
    max_age: 3600
  paths:
    "^/api/": # Appliquer CORS aux routes commençant par /api/
      allow_origin: ["*"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"]
      max_age: 3600
